language: python
python:
- 3.6
- 3.7
- 3.8
install: 
  - pip install -r requirements-dev.txt
  - curl -L "$(curl -Ls https://api.github.com/repos/terraform-linters/tflint/releases/latest | grep -o -E "https://.+?_linux_amd64.zip")" -o tflint.zip && unzip tflint.zip && rm tflint.zip
  - chmod +x tflint
script: 
  - make test
